<?php 
    session_start();
    if (!isset($_SESSION["user_id"])) { 
        header("Location: ../../index.html"); 
        exit(); 
    }
    if ($_SESSION["role"] != "1000") { 
        header("Location: ../unauthorized.html"); 
        exit(); 
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../styles/adminUI.css">
    <link rel="stylesheet" href="../styles/candidatesManager.css">
    <script src="../jquery.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candidates Manager</title>
</head>
<body>

    <div id="sidebar">
        <div id="title">
            <h1>Voting System</h1>
            <p>Admin Page</p>
        </div>
        <div id="menu_items">
            <a class="items" href="dashboard.php">Dashboard</a>
            <a class="items" href="./electionManager.php">Election Manager</a>
            <a class="items" href="./candidatesManager.php">Candidates Manager</a>
            <a class="items" href="./votersManager.php">Voters Manager</a>
            <a class="items" href="./adminSettings.php">Settings</a>
        </div>
    </div>

    <div id="main_content" class="candidates-page">

        <!-- Section 1: Select Election -->
        <div id="election_select_section">
            <label for="election_dropdown">Select Election</label>
            <select id="election_dropdown">
                <option value="">-- Loading elections... --</option>
            </select>
        </div>

        <!-- Section 2: View Toggle -->
        <div id="view_toggle_section">
            <button id="btn_manage_view" class="view_toggle_btn active">Manage Candidates</button>
            <button id="btn_slate_view"  class="view_toggle_btn">View Slate</button>
        </div>

        <!-- ═══════════════════════════════════════ -->
        <!--  MANAGE VIEW                            -->
        <!-- ═══════════════════════════════════════ -->
        <div id="manage_view">

            <!-- Party Tabs -->
            <div id="party_tabs_section">
                <div id="party_tabs_container">
                    <!-- Generated by JS -->
                </div>
            </div>

            <!-- Position Tabs -->
            <div id="tabs_section">
                <div id="tabs_container">
                    <!-- Generated by JS -->
                </div>
            </div>

            <!-- Current Candidates -->
            <div id="candidates_section">
                <h3>Current Candidates</h3>
                <div id="candidates_list"></div>
            </div>

            <!-- Add Candidate Panel -->
            <div id="add_candidate_section">
                <h3>Add a Candidate</h3>
                <input type="text" id="student_search_input" placeholder="Search student by name or ID...">
                <select id="student_dropdown"></select>
                <div id="selected_student_display">No student selected.</div>
                <button id="add_candidate_btn">Add Candidate</button>
                <div id="status_message"></div>
            </div>

        </div>

        <!-- ═══════════════════════════════════════ -->
        <!--  SLATE VIEW                             -->
        <!-- ═══════════════════════════════════════ -->
        <div id="slate_view">
            <div id="slate_container">
                <!-- Generated by JS -->
            </div>
        </div>

    </div>

    <script src="./candidatesManager.js"></script>
</body>
</html>